{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: api-gateway
    release: {{ .Release.Name }}
    environment: {{ .Values.global.environment }}
    component: ingress
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api-gateway
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.apiGateway.service.port }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: api-gateway
          image: "{{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}"
          imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiGateway.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.apiGateway.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.apiGateway.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.apiGateway.resources | nindent 12 }}
{{- end }}